namespace: bp-prod
image:
  backend: salob79/bp-backend:latest
  frontend: salob79/bp-frontend:latest
  mongo: mongo:7

host: bp.example.com

mongo:
  pvcName: mongo-pvc
  pvcSize: 5Gi
  storageClass: managed-csi
