namespace: bp-staging

nameOverride: bp-staging

image:
  backend: salob79/bp-backend:latest
  frontend: salob79/bp-frontend:latest
  mongo: mongo:7

host: bp.local

mongo:
  enabled: true
  pvcName: mongo-pvc
  pvcSize: 1Gi
  storageClass: managed-csi

ingress:
  name: bp-ingress
  className: nginx
  canary: false

service:
  frontend:
    name: frontend
    port: 80
  backend:
    name: backend
    port: 8080

backend:
  name: backend
  replicas: 2
  port: 8080
  mongoUri: mongodb://mongo:27017/bp

frontend:
  name: frontend
  replicas: 2
  port: 80
  apiBaseUrl: /api

certManager:
  enabled: true
  clusterIssuerName: letsencrypt-staging
  email: your-email@example.com
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  secretName: staging-tls
