name: Continuous Integration and Deployment (CI/CD) Workflow
description: |
  This workflow deploys the application to the specified environment.
  It is triggered manually and can be called from other workflows.
permissions:
  contents: write  # Grant write permissions for the entire workflow
# concurrency:
#   group: ${{ github.workflow }}
#   cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment to deploy to'
        required: true
        type: choice
        options:
          - staging
          - prod-canary
          - prod-stable
      trigger:
        description: 'Service that requires new release'
        required: false
        type: choice
        options:
          - 
          - frontend
          - backend

  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      trigger:
        required: false
        type: string

jobs:
  frontend:
    if: ${{ github.event.inputs.trigger == 'frontend' || github.event.inputs.trigger == '' }}
    uses: sianob/bp-frontend/.github/workflows/frontend-cicd.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  backend:
    if: ${{ github.event.inputs.trigger == 'backend' || github.event.inputs.trigger == '' }}
    uses: sianob/bp-backend/.github/workflows/backend-cicd.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  iac-staging:
    needs:
      - frontend
      # - backend
    # if: |
    #   (needs.frontend.result == 'success' && needs.backend.result == 'skipped') ||
    #   (needs.frontend.result == 'skipped' && needs.backend.result == 'success') ||
    #   (needs.frontend.result == 'success' && needs.backend.result == 'success')
    uses: sianob/bp-iac/.github/workflows/deploy.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    with:
      environment: staging
      action: 'create'

  # job-debug:
  #   needs: iac-staging
  #   runs-on: ubuntu-latest
  #   if: always()
  #   steps:
  #     - name: Dump job results
  #       run: |
  #         echo "Job Result: ${{ needs.iac-staging.result }}"
  #         echo "Job Outputs: ${{ toJson(needs.iac-staging.outputs) }}"
  #     - name: Dump GitHub Context
  #       run: echo '${{ toJson(github) }}'
  #     - name: Dump Needs Context
  #       run: echo '${{ toJson(needs) }}'

  #     - name: Verify Kube Context
  #       run: kubectl config get-contexts
  
  staging-deploy:
    needs: iac-staging
    if: ${{ needs.iac-staging.result == 'success' }}
    environment:
      name: staging
      url: https://staging.bp-calculator.com
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set kubeconfig secret (staging)
        run: |
          echo "${{ secrets.KUBECONFIG_STAGING }}" > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Verify Kube Context
        run: kubectl config get-contexts

      - name: Ensure Namespace exists
        run: |
          kubectl create namespace $(yq e '.namespace' ./bp-chart/values-staging.yaml) --dry-run=client -o yaml | kubectl apply -f -


      - name: Create TLS Secret
        run: |
          kubectl delete secret tls-secret --namespace $(yq e '.namespace' ./bp-chart/values-staging.yaml) --ignore-not-found
          echo "${{ secrets.TLS_CERT_B64 }}" | base64 -d > tls.crt
          echo "${{ secrets.TLS_KEY_B64 }}" | base64 -d > tls.key
          kubectl create secret tls tls-secret \
            --cert=tls.crt \
            --key=tls.key \
            --namespace $(yq e '.namespace' ./bp-chart/values-staging.yaml)

      - name: Get and bump latest release version
        run: |
          set -e

          # Try to get the latest tag, fallback to v0.0.0 if none exists
          latest_tag=$(gh release list --repo sianob/bp-deploy --limit 1 --json tagName --jq '.[0].tagName' || echo "")

          if [[ -z "$latest_tag" ]]; then
            echo "No previous release found. Using v0.0.0"
            version="0.0.0"
          else
            echo "Latest tag: $latest_tag"
            version="${latest_tag#Stable Production Version - }"
            version="${version#v}"  # remove 'v'

          fi

          # Split version and increment patch
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new_version="v$major.$minor.$patch"

          echo "New version: $new_version"
          echo "VERSION=$new_version" >> "$GITHUB_ENV"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}


      - name: Create GitHub Release
        run: |
          echo "Creating release ${{ env.VERSION }} in sianob/bp-deploy..."
          FRONTEND_RELEASE=$(gh release view -R sianob/bp-frontend --json name,url)
          FRONTEND_NAME=$(echo "$FRONTEND_RELEASE" | jq -r .name)
          FRONTEND_URL=$(echo "$FRONTEND_RELEASE" | jq -r .url)
          BACKEND_RELEASE=$(gh release view -R sianob/bp-backend --json name,url)
          BACKEND_NAME=$(echo "$BACKEND_RELEASE" | jq -r .name)
          BACKEND_URL=$(echo "$BACKEND_RELEASE" | jq -r .url)          
          gh api repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name="${{ env.VERSION }}" \
            -q .body >generated.md
          echo "## Deployment Details" >>generated.md
          echo "[Frontend: $FRONTEND_NAME]($FRONTEND_URL)" >>generated.md
          echo "[Backend: $BACKEND_NAME]($BACKEND_URL)" >>generated.md
          gh release create "${{ env.VERSION }}" \
            --repo "sianob/bp-deploy" \
            --title "${{ env.VERSION }}" \
            --notes-file generated.md
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Deploy with Helm
        run: |
          # kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
          helm upgrade --install bp-staging ./bp-chart \
            -f ./bp-chart/values-staging.yaml \
            --namespace $(yq e '.namespace' ./bp-chart/values-staging.yaml) \
            --create-namespace
  
      - name: Get Ingress IP
        run: |
          kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}' > ingress-ip.txt
          echo "Ingress IP: $(cat ingress-ip.txt)"
          echo "Deployment available at http://$(cat ingress-ip.txt)"

      # Azure login using service principal and secret
      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
    
      - name: Update DNS A record
        run: |
          DNS_NAME="staging"
          echo "Creating/updating DNS record for $DNS_NAME..."
          az network dns record-set a create \
            --resource-group "rg-monitoring-bp" \
            --zone-name "bp-calculator.com" \
            --name "$DNS_NAME" \
            --ttl 300
          az network dns record-set a add-record \
            --resource-group "rg-monitoring-bp" \
            --zone-name "bp-calculator.com" \
            --record-set-name "$DNS_NAME" \
            --ipv4-address "$(cat ingress-ip.txt)"

  performance-tests:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: staging-deploy
    env:
      WEB_APP_URI: 'staging.bp-calculator.com'
    steps:

      # Checkout the project
      - name: Checkout
        uses: actions/checkout@v4
      
      # Performance Tests    
      - name: Run K6 Performance Tests
        run: |
          docker pull grafana/k6
          pwd
          ls -la
          docker run -v $GITHUB_WORKSPACE/performance-tests:/opt/ -i grafana/k6 run /opt/k6-staging.js
  ui-tests:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: staging-deploy
    env:
      WEB_APP_URI: 'staging.bp-calculator.com'
    steps:

      # Checkout the project
      - name: Checkout
        uses: actions/checkout@v4
      
      # Performance Tests    
      - name: Run K6 Performance Tests
        run: |
          docker pull grafana/k6
          pwd
          ls -la
          docker run -v $GITHUB_WORKSPACE/performance-tests:/opt/ -i grafana/k6 run /opt/k6-staging.js
  canary:
    name: Deploy Canary
    needs:
      - performance-tests
      - ui-tests
    runs-on: ubuntu-latest
    environment:
      name: prod-canary

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: sianob/bp-deploy
          ref: main     

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set kubeconfig secret (prod)
        run: |
          echo "${{ secrets.KUBECONFIG_PROD }}" > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Verify Kube Context
        run: kubectl config get-contexts

      - name: Deploy with Helm
        run: |
          # kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

          helm upgrade --install bp-prod-canary ./bp-chart \
            -f ./bp-chart/values-prod-canary.yaml \
            --namespace $(yq e '.namespace' ./bp-chart/values-prod-canary.yaml) \
            --create-namespace
      # yq pre-installed
      # - name: Install yq
      #   run: sudo apt-get install -y yq

      - name: Update image tags
        env:
          BACKEND_NAME: ${{needs.staging-deploy.outputs.backend_name}}
          FRONTEND_NAME: ${{needs.staging-deploy.outputs.frontend_name}}
        run: |
          FRONTEND_RELEASE=$(gh release view -R sianob/bp-frontend --json name)
          FRONTEND_NAME=$(echo "$FRONTEND_RELEASE" | jq -r .name)
          BACKEND_RELEASE=$(gh release view -R sianob/bp-backend --json name)
          BACKEND_NAME=$(echo "$BACKEND_RELEASE" | jq -r .name)
          yq e -i ".image.backend="salob79/bp-backend:\"$BACKEND_NAME\"" ./bp-chart/values-prod-stable.yaml
          yq e -i ".image.frontend="salob79/bp-frontend:\"$FRONTEND_NAME\"" ./bp-chart/values-prod-stable.yaml
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          VERSION: ${{ env.VERSION }}
        run: |
          branch="update-prod-stable-${{ env.VERSION }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b "$branch"
          git add bp-chart/values-prod-stable.yaml
          git commit -m "Update image tags for prod-stable to ${{ env.VERSION }}"
          git push origin "$branch"
          gh pr create --title "Update prod-stable image tags to ${{ env.VERSION }}" \
            --body "This PR updates image tags for frontend/backend in prod-stable." \
            --base main --head "$branch"


  prod-ready:
    name: Release Sign-off
    environment:
      name: prod-stable
      url: https://prod.bp-calculator.com
    runs-on: ubuntu-latest
    needs:
      - canary

    steps:
      - name: Update GitHub Release
        run: |
          latest_tag=$(gh release list --repo sianob/bp-deploy --limit 1 --json tagName --jq '.[0].tagName')

          gh release edit $latest_tag \
            --repo ${{ github.repository }} \
            --title "Stable Production Version - $latest_tag"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # or GH_PAT if needed


  iac-prod:
    needs: prod-ready
    uses: sianob/bp-iac/.github/workflows/deploy.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    with:
      environment: prod
      action: 'create'

  deploy-prod:
    needs: prod-ready
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set kubeconfig secret (staging)
        run: |
          echo "${{ secrets.KUBECONFIG_PROD }}" >kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Verify Kube Context
        run: kubectl config get-contexts

      - name: Ensure Namespace exists
        run: |
          kubectl create namespace $(yq e '.namespace' ./bp-chart/values-prod-stable.yaml) --dry-run=client -o yaml | kubectl apply -f -


      - name: Create TLS Secret
        run: |
          kubectl delete secret tls-secret --namespace $(yq e '.namespace' ./bp-chart/values-prod-stable.yaml) --ignore-not-found
          echo "${{ secrets.TLS_CERT_B64 }}" | base64 -d > tls.crt
          echo "${{ secrets.TLS_KEY_B64 }}" | base64 -d > tls.key
          kubectl create secret tls tls-secret \
            --cert=tls.crt \
            --key=tls.key \
            --namespace $(yq e '.namespace' ./bp-chart/values-prod-stable.yaml)


      - name: Deploy with Helm
        run: |
          helm upgrade --install bp-prod-stable ./bp-chart \
            -f ./bp-chart/values-prod-stable.yaml \
            --namespace $(yq e '.namespace' ./bp-chart/values-prod-stable.yaml) \
            --create-namespace
  
      - name: Get Ingress IP
        run: |
          kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}' > ingress-ip.txt
          echo "Ingress IP: $(cat ingress-ip.txt)"
          echo "Deployment available at http://$(cat ingress-ip.txt)"

      # Azure login using service principal and secret
      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
    
      - name: Update DNS A record
        run: |
          DNS_NAME="prod"
          echo "Creating/updating DNS record for $DNS_NAME..."
          az network dns record-set a create \
            --resource-group "rg-monitoring-bp" \
            --zone-name "bp-calculator.com" \
            --name "$DNS_NAME" \
            --ttl 300
          az network dns record-set a add-record \
            --resource-group "rg-monitoring-bp" \
            --zone-name "bp-calculator.com" \
            --record-set-name "$DNS_NAME" \
            --ipv4-address "$(cat ingress-ip.txt)"
