name: Continuous Integration and Deployment

permissions:
  contents: write  # Grant write permissions for the entire workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment to deploy to'
        required: true
        type: choice
        options:
          - staging
          - prod-canary
          - prod-stable

  workflow_call:
    inputs:
      environment:
        required: false
        type: string

jobs:
  frontend:
    uses: sianob/bp-frontend/.github/workflows/frontend-cicd.yml@main
 