name: Continuous Integration and Deployment (CI/CD) Workflow
description: |
  This workflow deploys the application to the specified environment.
  It is triggered manually and can be called from other workflows.
permissions:
  contents: write  # Grant write permissions for the entire workflow
# concurrency:
#   group: ${{ github.workflow }}
#   cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment to deploy to'
        required: true
        type: choice
        options:
          - staging
          - prod-canary
          - prod-stable
      trigger:
        description: 'Service that requires new release'
        required: false
        type: choice
        options:
          - 
          - frontend
          - backend

  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      trigger:
        required: false
        type: string

jobs:
  frontend:
    if: ${{ github.event.inputs.environment == 'staging' && (github.event.inputs.trigger == 'frontend' || github.event.inputs.trigger == '') }}
    uses: sianob/bp-frontend/.github/workflows/frontend-cicd.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  backend:
    if: ${{ github.event.inputs.environment == 'staging' && (github.event.inputs.trigger == 'backend' || github.event.inputs.trigger == '') }}
    uses: sianob/bp-backend/.github/workflows/backend-cicd.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  iac:
    needs: [frontend, backend]
    if: |
      (needs.frontend.result == 'success' && !needs.backend.result) ||
      (needs.backend.result == 'success' && !needs.frontend.result) ||
      (needs.frontend.result == 'success' && needs.backend.result == 'success')
    runs-on: ubuntu-latest
    uses: sianob/bp-iac/.github/workflows/deploy.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    with:
      environment: ${{ github.event.inputs.environment == 'staging' && 'staging' || 'prod' }}
      action: 'create'

  staging-deploy:
    environment:
      name: ${{ github.event.inputs.environment }}
      url: https://staging.bp-calculator.com
    needs: iac
    with:
      environment: ${{ github.event.inputs.environment }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set kubeconfig secret (staging)
        if: github.event.inputs.environment == 'staging'
        run: |
          echo "${{ secrets.KUBECONFIG_STAGING }}" > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Set kubeconfig secret (prod)
        if: github.event.inputs.environment == 'prod-canary' || github.event.inputs.environment == 'prod-stable'
        run: |
          echo "${{ secrets.KUBECONFIG_PROD }}" > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Verify Kube Context
        run: kubectl config get-contexts

      - name: Ensure Namespace exists
        run: |
          kubectl create namespace $(yq e '.namespace' ./bp-chart/values-${{ github.event.inputs.environment }}.yaml) --dry-run=client -o yaml | kubectl apply -f -


      - name: Create TLS Secret
        run: |
          kubectl delete secret tls-secret --namespace $(yq e '.namespace' ./bp-chart/values-${{ github.event.inputs.environment }}.yaml) --ignore-not-found
          echo "${{ secrets.TLS_CERT_B64 }}" | base64 -d > tls.crt
          echo "${{ secrets.TLS_KEY_B64 }}" | base64 -d > tls.key
          kubectl create secret tls tls-secret \
            --cert=tls.crt \
            --key=tls.key \
            --namespace $(yq e '.namespace' ./bp-chart/values-${{ github.event.inputs.environment }}.yaml)

      - name: Get and bump latest release version
        run: |
          set -e

          # Try to get the latest tag, fallback to v0.0.0 if none exists
          latest_tag=$(gh release list --repo sianob/bp-deploy --limit 1 --json tagName --jq '.[0].tagName' || echo "")

          if [[ -z "$latest_tag" ]]; then
            echo "No previous release found. Using v0.0.0"
            version="0.0.0"
          else
            echo "Latest tag: $latest_tag"
            version="${latest_tag#v}"  # remove 'v'
          fi

          # Split version and increment patch
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new_version="v$major.$minor.$patch"

          echo "New version: $new_version"
          echo "VERSION=$new_version" >> "$GITHUB_ENV"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}


      - name: Create GitHub Release
        run: |
          echo "Creating release ${{ env.VERSION }} in sianob/bp-deploy..."
          FRONTEND_RELEASE=$(gh release view -R sianob/bp-frontend --json name,url)
          FRONTEND_NAME=$(echo "$FRONTEND_RELEASE" | jq -r .name)
          FRONTEND_URL=$(echo "$FRONTEND_RELEASE" | jq -r .url)
          BACKEND_RELEASE=$(gh release view -R sianob/bp-backend --json name,url)
          BACKEND_NAME=$(echo "$BACKEND_RELEASE" | jq -r .name)
          BACKEND_URL=$(echo "$BACKEND_RELEASE" | jq -r .url)          
          gh api repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name="${{ env.VERSION }}" \
            -q .body >generated.md
          echo "## Deployment Details" >>generated.md
          echo "[Frontend: $FRONTEND_NAME]($FRONTEND_URL)" >>generated.md
          echo "[Backend: $BACKEND_NAME]($BACKEND_URL)" >>generated.md
          gh release create "${{ env.VERSION }}" \
            --repo "sianob/bp-deploy" \
            --title "${{ env.VERSION }}" \
            --notes-file generated.md
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install bp-${{ github.event.inputs.environment }} ./bp-chart \
            -f ./bp-chart/values-${{ github.event.inputs.environment }}.yaml \
            --namespace $(yq e '.namespace' ./bp-chart/values-${{ github.event.inputs.environment }}.yaml) \
            --create-namespace
  
      - name: Get Ingress IP
        run: |
          kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}' > ingress-ip.txt
          echo "Ingress IP: $(cat ingress-ip.txt)"
          echo "Deployment available at http://$(cat ingress-ip.txt)"

      # Azure login using service principal and secret
      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
    
      - name: Update DNS A record
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
            DNS_NAME="staging"
          else
            DNS_NAME="prod"
          fi

          echo "Creating/updating DNS record for $DNS_NAME..."
          az network dns record-set a create \
            --resource-group "rg-monitoring-bp" \
            --zone-name "bp-calculator.com" \
            --name "$DNS_NAME" \
            --ttl 300
          az network dns record-set a add-record \
            --resource-group "rg-monitoring-bp" \
            --zone-name "bp-calculator.com" \
            --record-set-name "$DNS_NAME" \
            --ipv4-address "$(cat ingress-ip.txt)"

  performance-tests:
    if: github.event.inputs.environment == 'staging'
    runs-on: ubuntu-latest
    permissions: write-all
    needs: staging-deploy
    env:
      WEB_APP_URI: 'staging.bp-calculator.com'
    steps:

      # Checkout the project
      - name: Checkout
        uses: actions/checkout@v4
      
      # Performance Tests    
      - name: Run K6 Performance Tests
        run: |
          docker pull grafana/k6
          pwd
          ls -la
          docker run -v $GITHUB_WORKSPACE/performance-tests:/opt/ -i grafana/k6 run /opt/k6-staging.js
  ui-tests:
    if: github.event.inputs.environment == 'staging'
    runs-on: ubuntu-latest
    permissions: write-all
    needs: staging-deploy
    env:
      WEB_APP_URI: 'staging.bp-calculator.com'
    steps:

      # Checkout the project
      - name: Checkout
        uses: actions/checkout@v4
      
      # Performance Tests    
      - name: Run K6 Performance Tests
        run: |
          docker pull grafana/k6
          pwd
          ls -la
          docker run -v $GITHUB_WORKSPACE/performance-tests:/opt/ -i grafana/k6 run /opt/k6-staging.js
  # canary:
  #   uses: ./.github/workflows/deploy.yml
  #   runs-on: ubuntu-latest
  #   with:
  #     environment: prod-canary
  #   needs: 
  #     - performance-tests
  #     - ui-tests

  # deploy-prod:
  #   environment:
  #     name: ${{ github.event.inputs.environment }}
  #     url: https://prod.bp-calculator.com
  #   uses: ./.github/workflows/cicd.yml
  #   runs-on: ubuntu-latest
  #   with:
  #     environment: prod-stable
  #   needs: 
  #     - performance-tests
  #     - ui-tests